### ISSUE TITLE
CI: use bmwill's rust cache

### ISSUE THREAD

**Issue by huitseeker** [argumentcomputer/zk-light-clients#167]
- aptos LC under the aptos feature imports rocksdb-sys via aptos,
- rocksdb-sys get rebuilt (to identical results) on every single CI build because it's not cached,
- it's not cached because its paths aren't included in [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache),
- we use Swatinem/rust-cache via [ci-workflows](https://github.com/argumentcomputer/ci-workflows)
- however the rocksdb paths are included in [bmwill/rust-cache](https://github.com/bmwill/rust-cache) which was created for this reason.

We should use the later, not the former and spare ourselves the minutes of wait.

**Comment by samuelburnham** [comment]
Could you provide an example log where this is happening? The `librocksdb-sys` caching issue should be fixed per https://github.com/Swatinem/rust-cache/commit/f6987ea139b70babe623061b3b9c01a93ea71187, which caches `*-sys` crates in `~/.cargo/registry/src`. See https://github.com/Swatinem/rust-cache/issues/150 and https://github.com/Swatinem/rust-cache/issues/100 for discussion.

**Comment by huitseeker** [comment]
Oh, wow, I think you're right. I thought I had seen a recompilation line, which triggered me writing this issue, but I can't find it any more. This might well be fixed. Thanks for the pointers!
