### ISSUE TITLE
Operational bridge documentation

### ISSUE THREAD

**Issue by wwared** [argumentcomputer/zk-light-clients#293]
We should clarify a bit more, in our documentation, the following items:

* How to run the proof server for a given LC, and what tunable parameters are there (e.g. RPC URL)
* How to run and modify the client for a production bridge, in particular: (no need for the real modifications, just indicating on the source)
  * Where should the proof be assembled into a transaction and sent over to the corresponding network?
  * How/where to modify the inclusion/SPV proofs to target specific transactions of interest to the bridge?
* Some clarity around the changes needed to wrap the verifier contracts with a proper bridge contract.

(This is of particular interest on the Kadena/Ethereum LCs)

**Comment by huitseeker** [comment]
Fixed in https://github.com/argumentcomputer/zk-light-clients/pull/298 https://github.com/argumentcomputer/zk-light-clients/pull/297  /cc @tchataigner @wwared
